import dbConnect from '../../lib/dbConnect';
import Cities from '../../models/Cities';
import slugify from 'slugify';

const insertCity = async(item) => {
    const city = new Cities({
        'name' : item.name,
        'slug' : slugify(item.name).toLowerCase()
    });
    city.save(function (err) {
        if (err) return handleError(err);
        // saved!
    });
}

export default async(req,res)=>{

    var cities = [
        {"name": "Atlantis"},
        {"name": "Ave Maria"},
        {"name": "Aventura"},
        {"name": "Bal Harbour"},
        {"name": "Barefoot Bay"},
        {"name": "Bay Harbor Islands"},
        {"name": "Belle Glade"},
        {"name": "Big Pine"},
        {"name": "Biscayne Gardens"},
        {"name": "Biscayne Park"},
        {"name": "Boca Raton"},
        {"name": "Bonita Springs"},
        {"name": "Boynton Beach"},
        {"name": "Bradenton"},
        {"name": "Brandon"},
        {"name": "Bulkhead Ridge"},
        {"name": "Canal Point"},
        {"name": "Cape Canaveral"},
        {"name": "Cape Coral"},
        {"name": "Clearwater"},
        {"name": "Clermont"},
        {"name": "Clewiston"},
        {"name": "Cocoa"},
        {"name": "Coconut Creek"},
        {"name": "Coconut Grove"},
        {"name": "Cooper City"},
        {"name": "Coral Gables"},
        {"name": "Coral Springs"},
        {"name": "Cresent City"},
        {"name": "Cutler Bay"},
        {"name": "Dania Beach"},
        {"name": "Davenport"},
        {"name": "Davie"},
        {"name": "Daytona"},
        {"name": "Deerfield Beach"},
        {"name": "Deland"},
        {"name": "Delray Beach"},
        {"name": "Deltona"},
        {"name": "Doral"},
        {"name": "Eastern Shores"},
        {"name": "El Portal"},
        {"name": "Englewood"},
        {"name": "Fisher Island"},
        {"name": "Florida City"},
        {"name": "Fort Lauderdale"},
        {"name": "Fort Myers"},
        {"name": "Fort Pierce"},
        {"name": "Frostproof"},
        {"name": "Gainesville"},
        {"name": "Golden Beach"},
        {"name": "Goulds"},
        {"name": "Green Acres"},
        {"name": "Hallandale Beach"},
        {"name": "Haverhill"},
        {"name": "Hialeah"},
        {"name": "Hialeah Gardens"},
        {"name": "Highland Beach"},
        {"name": "Hillsboro Beach"},
        {"name": "Hobe Sound"},
        {"name": "Hollywood"},
        {"name": "Homestead"},
        {"name": "Homosassa Springs"},
        {"name": "Hudson"},
        {"name": "Hutchinson Island"},
        {"name": "Hypoluxo"},
        {"name": "Indian Town"},
        {"name": "Inverness"},
        {"name": "Islamorada"},
        {"name": "Jacksonville"},
        {"name": "Jensen Beach"},
        {"name": "Juno Beach"},
        {"name": "Jupiter"},
        {"name": "Jupiter Inlet Colony"},
        {"name": "Kendall"},
        {"name": "Key Biscayne"},
        {"name": "Key Largo"},
        {"name": "Key West"},
        {"name": "Kissimmee"},
        {"name": "La Belle"},
        {"name": "Lake Clarke Shores"},
        {"name": "Lakeland"},
        {"name": "Lake Park"},
        {"name": "Lake Placid"},
        {"name": "Lake Port"},
        {"name": "Lake Wales"},
        {"name": "Lake Worth"},
        {"name": "Lantana"},
        {"name": "Lauderdale By The Sea"},
        {"name": "Lauderdale Lakes"},
        {"name": "Lauderhill"},
        {"name": "Lazy Lake"},
        {"name": "Lehigh Acres"},
        {"name": "Lighthouse Point"},
        {"name": "Loxahatchee"},
        {"name": "Malabar"},
        {"name": "Manalapan"},
        {"name": "Mangonia Park"},
        {"name": "Marathon"},
        {"name": "Marco Island"},
        {"name": "Margate"},
        {"name": "Medley"},
        {"name": "Melbourne"},
        {"name": "Melbourne Beach"},
        {"name": "Miami"},
        {"name": "Miami Beach"},
        {"name": "Miami Gardens"},
        {"name": "Miami Lakes"},
        {"name": "Miami Shores"},
        {"name": "Miami Springs"},
        {"name": "Miramar"},
        {"name": "Moore Haven"},
        {"name": "Mount Dora"},
        {"name": "Naples"},
        {"name": "Naranja"},
        {"name": "New Port Richey"},
        {"name": "North Bay Village"},
        {"name": "North Lauderdale"},
        {"name": "North Miami"},
        {"name": "North Miami Beach"},
        {"name": "North Palm Beach"},
        {"name": "North Port"},
        {"name": "Oakland Park"},
        {"name": "Ocala"},
        {"name": "Ocean Ridge"},
        {"name": "Okeechobee"},
        {"name": "Opa-Locka"},
        {"name": "Orlando"},
        {"name": "Ormond Beach"},
        {"name": "Other City - In The State Of Florida"},
        {"name": "Other City - Not In The State Of Florida"},
        {"name": "Other Country - Not In USA"},
        {"name": "OTHER FL Key"},
        {"name": "Pahokee"},
        {"name": "Palatka"},
        {"name": "Palm Bay"},
        {"name": "Palm Beach"},
        {"name": "Palm Beach Gardens"},
        {"name": "Palm Beach Shores"},
        {"name": "Palm City"},
        {"name": "Palm Coast"},
        {"name": "Palmetto Bay"},
        {"name": "Palm Harbor"},
        {"name": "Palm Springs"},
        {"name": "Panama City"},
        {"name": "Parkland"},
        {"name": "Pembroke Park"},
        {"name": "Pembroke Pines"},
        {"name": "Perrine"},
        {"name": "Pinecrest"},
        {"name": "Plantation"},
        {"name": "Plant City"},
        {"name": "Pompano Beach"},
        {"name": "Port Charlotte"},
        {"name": "Port Orange"},
        {"name": "Port St. Lucie"},
        {"name": "Punta Gorda"},
        {"name": "Riverview"},
        {"name": "Riviera Beach"},
        {"name": "Royal Palm Beach"},
        {"name": "Saint Cloud"},
        {"name": "Saint Lucie West"},
        {"name": "Sarasota"},
        {"name": "Satellite Beach"},
        {"name": "Sea Ranch Lakes"},
        {"name": "Sebastian"},
        {"name": "Sebring"},
        {"name": "Singer Island"},
        {"name": "South Bay"},
        {"name": "South Miami"},
        {"name": "South Palm Beach"},
        {"name": "Southwest Ranches"},
        {"name": "Spring Hill"},
        {"name": "St Augustine"},
        {"name": "St Petersburg"},
        {"name": "Stuart"},
        {"name": "Sugarloaf"},
        {"name": "Sunny Isles Beach"},
        {"name": "Sunrise"},
        {"name": "Surfside"},
        {"name": "Sweetwater"},
        {"name": "Tallahassee"},
        {"name": "Tamarac"},
        {"name": "Tampa"},
        {"name": "Tavernier"},
        {"name": "Tequesta"},
        {"name": "The Villages"},
        {"name": "Titusville"},
        {"name": "Unincorporated Broward County"},
        {"name": "Unincorporated Dade County"},
        {"name": "Unincorporated Palm Beach County"},
        {"name": "Venice"},
        {"name": "Vero Beach"},
        {"name": "Virginia Gardens"},
        {"name": "Wellington"},
        {"name": "Westlake"},
        {"name": "West Melbourne"},
        {"name": "West Miami"},
        {"name": "Weston"},
        {"name": "West Palm Beach"},
        {"name": "West Park"},
        {"name": "Wildwood"},
        {"name": "Williston"},
        {"name": "Wilton Manors"},
        {"name": "Winter Garden"},
        {"name": "Winter Haven"},
        {"name": "Winter Park"},
        {"name": "Zephyrhills"}
    ];

    await dbConnect();
    try{
        cities.forEach(item => {
            insertCity(item);
        });

        res.status(200).send('Ok');
    } catch(err){
        res.status(500).json({
            error : "something went wrong, try again later",
            mesage : err
        });
    }
}
